esphome:
  name: bedroom-ac
  friendly_name: bedroom_ac

external_components:
  - source: github://chris4824/esphome_airconintl@packaging

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf
 # With changes of 2025.2.0 adding lines below will allow build
 #   version: 4.4.8
 #   platform_version: 5.4.0

    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
      CONFIG_AUDIO_BOARD_CUSTOM: "y"

uart:
  tx_pin: 1
  rx_pin: 3
  baud_rate: 9600
  debug:

climate:
  - platform: airconintl
    name: "Bedroom AC"
    temperature_unit: "F"
    re_pin: GPIO12
    de_pin: GPIO13
    compressor_frequency:
      name: "Compressor Frequency"
    compressor_frequency_setting:
      name: "Compressor Frequency Setting"
    compressor_frequency_send:
      name: "Compressor Frequency Send"
    outdoor_temperature:
      name: "Outdoor Temperature"
    outdoor_condenser_temperature:
      name: "Outdoor Condenser Temperature"
    compressor_exhaust_temperature:
      name: "Compressor Exhaust Temperature"
    target_exhaust_temperature:
      name: "Target Exhaust Temperature"
    indoor_pipe_temperature:
      name: "Indoor Evaporator Inlet Temperature"
    humidity_setpoint:
      name: "Indoor Humidity setting"
    humidity_status:
      name: "Indoor Humidity status"

switch:
  - platform: restart
    name: "AC controller restart"

# Enable logging
logger:
  level: VERBOSE
  baud_rate: 0
  
# Enable Home Assistant API
api:
  encryption:
    key: "xoYWZoh6ffxvcGP/Cg1IUzQJWby98RexhBt9PseT0Ms="

ota:
  - platform: esphome
    password: "943fe7ce1f0303f89131c6d9578ef29d"

wifi:
  ssid: !secret wifi_ssid_iot
  password: !secret wifi_password_iot

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Garage-Ac Fallback Hotspot"
    password: "pLWgQiIbKX2w"

captive_portal: