esphome:
  name: livingroom-ac
  friendly_name: livingroom_ac

external_components:
  - source:
      type: local
      path: /config/esphome/external_components

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf
 # With changes of 2025.2.0 adding lines below will allow build
 #   version: 4.4.8
 #   platform_version: 5.4.0

    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
      CONFIG_AUDIO_BOARD_CUSTOM: "y"

uart:
  tx_pin: 1
  rx_pin: 3
  baud_rate: 9600
  debug:

climate:
  - platform: airconintl
    id: livingroom_ac
    name: "Living Room AC"
    temperature_unit: "F"
    re_pin: GPIO12
    de_pin: GPIO13
    compressor_frequency:
      name: "Compressor Frequency"
    compressor_frequency_setting:
      name: "Compressor Frequency Setting"
    compressor_frequency_send:
      name: "Compressor Frequency Send"
    outdoor_temperature:
      name: "Outdoor Temperature"
      unit_of_measurement: "°F"         # Set the unit string
      filters:
        - lambda: 'return x * 1.8 + 32.0;' # The conversion logic
    outdoor_condenser_temperature:
      name: "Outdoor Condenser Temperature"
      unit_of_measurement: "°F"         # Set the unit string
      filters:
        - lambda: 'return x * 1.8 + 32.0;' # The conversion logic
    compressor_exhaust_temperature:
      name: "Compressor Exhaust Temperature"
      unit_of_measurement: "°F"         # Set the unit string
      filters:
        - lambda: 'return x * 1.8 + 32.0;' # The conversion logic
    target_exhaust_temperature:
      name: "Target Exhaust Temperature"
      unit_of_measurement: "°F"         # Set the unit string
      filters:
        - lambda: 'return x * 1.8 + 32.0;' # The conversion logic
    indoor_pipe_temperature:
      name: "Indoor Evaporator Inlet Temperature"
      unit_of_measurement: "°F"         # Set the unit string
      filters:
        - lambda: 'return x * 1.8 + 32.0;' # The conversion logic

# ──────────────────────────────────────────────────────────────
#  Fahrenheit target temperature with a real slider in HA
# ──────────────────────────────────────────────────────────────
number:
  - platform: template
    name: "Living Room Target Temperature"
    id: livingroom_ac_target_temp_f
    unit_of_measurement: "°F"
    icon: "mdi:thermostat"
    device_class: temperature
    min_value: 60
    max_value: 90
    step: 1
    optimistic: true
    restore_value: true
    set_action:
      - climate.control:
          id: livingroom_ac
          target_temperature: !lambda 'return (x - 32.0) / 1.8;'

# ──────────────────────────────────────────────────────────────
#  Current room temperature sensor in Fahrenheit (read-only)
# ──────────────────────────────────────────────────────────────
sensor:
  - platform: template
    name: "Living Room AC Current Temperature"
    id: livingroom_ac_current_temp_f
    unit_of_measurement: "°F"
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 1
    lambda: |-
      return id(livingroom_ac).current_temperature * 1.8 + 32.0;

web_server:
  port: 80
  version: 3
  local: true  # Embeds JS/CSS locally — fixes blank pages without internet
  css_url: ""  # Disable external CSS
  js_url: ""   # Disable external JS

switch:
  - platform: restart
    name: "AC controller restart"

# Enable logging
logger:
  level: VERBOSE
  baud_rate: 0
  
# Enable Home Assistant API
api:
  encryption:
    key: "xoYWZoh6ffxvcGP/Cg1IUzQJWby98RexhBt9PseT0Ms="

ota:
  - platform: esphome
    password: "943fe7ce1f0303f89131c6d9578ef29d"

wifi:
  ssid: !secret wifi_ssid_iot
  password: !secret wifi_password_iot

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Garage-Ac Fallback Hotspot"
    password: "pLWgQiIbKX2w"

captive_portal: